%%
load('cifar10NetRCNN.mat', 'cifar10NetRCNN');
cifar10Net=cifar10NetRCNN;
cifar10Net.Network.Layers
%%
bx1=[annotations.bbox_x1];
bx2=[annotations.bbox_x2];
by1=[annotations.bbox_y1];
by2=[annotations.bbox_y2];
data=[bx1 bx2 by1 by2];

options=trainingOptions('sgdm', ...
    'Momentum', 0.9, ...
    'InitialLearnRate', 0.005, ...
    'LearnRateSchedule', 'piecewise', ...
    'LearnRateDropFactor', 0.1, ...
    'LearnRateDropPeriod',128, ...
    'L2Regularization',0.01, ...
    'MaxEpochs', 100, ...
    'MiniBatchSize', 100, ...
    'Verbose', true);)
cifar10NetRCNN_new= trainRCNNObjectDetector(data, cifar10Net, options, ...
    'NegativeOverlapRange', [0 0.2], 'PositiveOverlapRange',[0.7 1])
%可以改现有的该网络的全连接层为我训练的RCNN层
%%
testImage=imread('cars_train_nocrop/00020.jpg');
testImage_=imresize(testImage,[227 227]);
TypeNum=classify(cifar10NetRCNN_new,testImage_);
TypeName=class_names(TypeNum);
disp(TypeName);
figure;
imshow(testImage);